:PROPERTIES:
:ID:       1579118d-2a92-4078-a874-b73221e08e86
:END:
#+title: quantum computing requires a different IP regime to protect competition and innovation
#+filetags: :intellectual_property:quantum:
#+cite_export: csl ~/Zotero/styles/oscola.csl

The key arguments that the author[cite:@kopRegulatingTransformativeTechnology2020] makes are: 

1. Subsystems within a quantum computer, can be either be developed by humans, or a result of mechanistic creation. As long as it is mechanistic creation it must belong to the public domain for people to use. Human creations must not be 'over-protected'. Indefinite control over discoveries leads to a monopoly. Access to R&D infra also plays role. Centralisation could also cause problems with transparency. 
3. The use of 'state secrets' to protect quantum research will seriously impact competition and research. There is a need to accommodate participation with security.
4. Introduce *shorter IP protection duration* developing in  tandem with the pace of innovation. Each innovation will last for 3-10 years. Diminish instances of complete monopoly and allow further R&D in this realm. 








