:PROPERTIES:
:ID:       f25e02f8-ca9e-4cb6-8f24-6f92545453f2
:END:
#+title: anonymity maintains neutrality in religious discussion online

Spanish researchers, brought about an interesting issue concerning the importance of *anonymity and neutrality* in online religious expression.[cite:@astor_2024]

Their key insights were
1. Neutrality is important for religious reference website's online. This helps present authenticity. They position themselves as being non-partisan individuals working with the objective of presenting Islam in its "true" state. They refrain from leaning towards or against any particular school of Islamic Jurisprudence.
2. Anonymity helps to obfuscate information that may dent this appearance of neutrality. This includes geographical information, or the identity of sect. It allows for open and fearless expression. Author's observe that forums which allow for anonymity also permit individuals to ask sensitive questions which they may not be permitted to within the confines of their social ecosystem. The performance of anonymity contributes to the impression that the content is *universal and non-sectarian*. 

There is an implicit Lutherian method here.
Condemning 'bias' views of the scripture implies that hardline orthodoxy has given way to a democratic engagement with the text. This diversity in interpretation make religious reform far more difficul. It will allow creating sub-groups and cults that may entrench dogma and regressive interpretative practices in smaller communities.
