:PROPERTIES:
:ID:       7664daca-e08e-439f-bdd9-25667d8a9dd9
:END:
#+title: AI's data problem
#+cite_export: csl /home/kjani/Zotero/styles/oscola.csl


- Data sharing between two enterprise entites is not quite clear. Shopkeeper selling data, or Farmer selling data
- Can we improve the [[id:6094e3fa-2e35-4c1e-b695-52823cb51782][AI's blackbox problem]] through the use of open data-sets.
- How do you mediate the Governments relation with AI' companies, and their use of Public Data Sets. [cite:@OpenDataAI]
- What will the future look like when AI Companies come under the ambit of Article 12.
- Most interestingly, when a recidivism prediction algorithm was analysed, it was seen that it created race-inclined outcomes not because it was explicitly asked to do so, but because of age and criminal history.[cite:@angelinoLearningCertifiablyOptimal2018] This leads to two interesting conclusions:
  - That the use of this technology is bound to reciprocate the same biases that humans perpetrate. No form of AI Auditing can ensure that this is not the case.
  - That it is impossible to 'sensitise' AI to come to any other conclusion because that would also reduce the efficiency of the model. 
