:PROPERTIES:
:ID:       5ba80320-fda2-45cd-9a4a-2de334d1cdb0
:END:
#+title: The proble with mandated backdoors
#+cite_export: csl /home/kjani/Zotero/styles/oscola.csl


- National Security, Public Order and Crime
  - Citizen = Not the Other. Entire idea of sovereignty is couched in the language of Otherness.
  - Rohingya = Alien.
  - Treaty of Westphalia = Sovereignty  (I am willing to accept the validity of your borde as long as you continue to accept mine).
    - Sovreignty = Is a Wattime Declaration of Indivduality. Territorial and Spatial.
    - Continues to be formulated in adversarial terms = War.
    - Post-War GWO does not exist but we do have  Post-Westphalian GWO. Sovreignty  is contested because of complex interdependence = foundation of liberal gloabalisation.
    - Argue that MB is a symptom of anxiety and control. Question is how must this fear either be eliminated assuaged. And in this regard what is the role of the Constitution. As the formal declaration of sovereignty, how can the Constitution be read constructively to again /eliminate or assuade/ these fears.
    - Ghost-Busting. Spectre of Osama, Spectre of Mansood Azhar - Spectre of Sharjeel Imam      
- Habermas - Public Sphere. Control of Coffee Table.
- The Right to Encryption - On a Personal Level. 
