:PROPERTIES:
:ID:       87b50090-a75f-48b4-80ab-9c7092700c6e
:END:
#+title: Constitution as a Moral Document


Nariman writes:
#+begin_quote
When we gave ourselves a constitution it was certainly good to provide rights enforceable against the state and state agencies. But I believe that it would have made a difference to our attitudes and our national consciousness if we had stressed also the responsibilities of one citizen to another.

Why did all of them – ministers, parliamentarians fail us? Was it a sense of fear? Some in high places did confess to it. I do not think this is true of persons holding key positions of power. For them, the only explanation is that they were not sufficiently imbued with the spirit of a written constitution. The constitution you see doesn’t work – never works – on its own: it depends on the wisdom and statesmanship of its constitutional functionaries.
#+end_quote

His argument finds force also in Ambedkar's statement:

#+begin_quote
"however good a constitution may be, if those who are implementing it are not good, it will prove to be bad"
#+end_quote

This is Ambedkar's spectre that exists beyond the realm of positive legal inquiry. It is the greater moral question that must be asked. In the presence of his spectre, mundane discussions on the nature and form of constitutional interpretation has no real value.
