:PROPERTIES:
:ID:       003b66a9-cec1-4c3f-b2c9-35038bfef378
:END:
#+title: User's Guide to Foccault

- Source: Cambridge Companion to Focault

Focucault is presented as developing a new method where he goies beyond
structuralism. For Dreyfus this is called interpretative analytics. analytics
because it shares Kant'ts concern for determining the sources of our concepts.
Interpretative because it aims to develop a pragmatically guided reading of the
coherence of the practices in which the conetpts are expressed. For them it is
the only position let that does not regress to tradition making it unteneable.
They intend to develop a general interpretation where they read whole of F work
as directed towards the development of a single historico-philosophical method
that is priviledged in modern analysis.

Author is unease with this interpreation as they deny 'specificity and
marginality' of F's work. The fact that each of his works donot refer to
previous works shows that they are specific to the particular discipline he is
challenging not determined by a general theory. cited methods of interpreation
suprpress his marginality by presenting F's work as the solution to the problems
of an established discipline. They fail to consider that F's call is to protect
from the dangers of disciline's entirely. The necessary presuppositions that
define disciplines have been identified and reproached in his works. Placing him
in a discipline thus makes the discourse self-contradictory. the author argues
that these interpretations (general) should not be renounced, but rather
regarded as non-unique and developed for specific purposes. It is however more
profitable to regard F as an intellecural artisan, who has construcred a variery
of arifacts. this specificity mst be maintained although an artifact may have
more uses than explicitly envisaged. 

Archeology and Genealogy are retrospective descriptions of F's efforts to come
to terms with historical material. The author argues that F's histories be
tackled around four dimensions - ideas concepts, present, experience. For F the
discintion between concepts and theory is that concepts interpret scientific
data and theories explain them. This is against the AA view that they deine the
concept in terms of which data is understood. concept may be used to provide for
methods that explain the given data, whereas theories provide differnent often
conflicting asnwers to these questions. concepts are thus theoretically
poluvalent but at the same time can function in different theoreticall contexts.
Galileo introduced falling bodies Newton provided a competing 'theory'. F most
importantly does not focus on concepts that are explicitly deployed by the
discipline but rather on concepts that create the condition fof possiblity for
the first odrder concept. this the author calls is 'intellectual subconcious'.
the play of an indviduals thought in a given period takes place in a space
within a structure defined by a system of rules fundamental than the assertion
of those thinkng in the space. Marking the strcutures of this space gives a
fundamental understanding of the history of thought rather than standard
histories centered on the inividual subject. 

He is thus a historian of the 'present'. F's histories begin with his perception
that something is worong with the present. that becomes the foundation of his
intellectual project which provides important context for the subsequent
historical analysis.  While existing histories suggest that the present is
inevitable given the historical causes, F points to a contingency in what
history has given us. F's history aims to remove this air of necessity by
showing that the past ordered things quitte differently and that the processes
leading to our present were by no means inevitable. He aims to show that the
classical and modern conceptions of madness are social constrcutions
intelligible and compelling in their own periods but having no acces to the
'truth of madness'. 
