:PROPERTIES:
:ID:       576f2a63-0d5b-4cb5-968c-a858249545bc
:END:
#+title: Founding Mothers of the Indian Constitution

Time is death - Tomorrow is today.
Would Satyavan have done the same - Savitri
The mode through which he owes form emotive to cognitive reading with Yagnavalkya and Janak dialogue = Women are debating men and often able to outperform. Mandan Mishra

Man - Woman
Rational - Emotive 
Inside - Outside 

By this logic law would be made by men. Elokeshi - causes the problem - Partha resolves this problem - through the ontic model. Chetan - When we tell ourselves that we give laws to ourselves, there are women in this discourse. 

Presence is very real but the absence is more real than the presence. What do you mean by the framing of the constitution - Derrida frame

WHen I look at you I look at you instantaneously. I look at you everything at once. The photo has a frame. There is a frame. There are people that are in, and that are not there. In the frame there is selection and deselection at the same time. 

Was the woman self-effacing or is the problem with the discipline. 

There is only one dalit woman
How do they deal with the question of modernity? Is the presence of 

I should be able to do what you will do - The definition of law

How does the women lawmaker look at the image of the male lawmaker looking at the problem of women. 

What is the defining moment of the women’s question? When did it resonate with the nationalist movement
    • Possibly post 1915, with the Bengal movement and Swadeshi movement.
    • It begins with the upper caste women 

French Revolution - Arendt
    • If you say the rights of man, one should have stopped there! Why go further?
    • Man is already a constructed identity; the use of the word ‘Citizen’ creates a boundary which creates the category of ‘inside the border’ and ‘outside the border’. 
    • It is the rights that create people who are dispossessed and refugees. She will then argue that 
    • When women are asking for rights they are using a category which is doubled edged. She could be asking rights qua human, but she does not do this because the category of human is asexualised. That everyone has the same body, humans are embodied beings. Whenever you bring body in the law the law will ensure that there is some form of homogeneity. 
    • This leads to a mere formal rights regime because implicitly being human is like being male. They have to thus ask for two things: they had to first prove that they are human, and then they had to ask for rights as women. 
        ◦ Equality is a problem, what is more needed : recognise that we are human + then recognise us as women.
    • Human Rights is a moral right against whom?

It creates the same problem that the French Revolution created - create a category that is so wide that it encompasses everything; “MAN”. This is similar to the woman's question, formulating a category that is so wide that it makes the project of rights difficult. 

Women have been responding to the crisis since the 1930's but they have posited that it must not be thrusted. In 1921 someone made the kind of argument when Women’s literacy is 3%, imagine how out of place it would have sounded at the time. 

If Bose Patel and Savarkar are the ultra masculinist and if Gandhi is a woman, then Ambedkar is a trans person. He is the only one who constantly supports the women's issue. If women are ½ the man. Until 2005 we have to wait to say 1=1. If you look at the logic, Ambedkar is a male but he is ⅛ male while the upper caste are 100% male. His masculinity is contested because he is dalit. Ambedkar almost has a consciousness because he has himself gone through so much. Ambedkar knows what these upper caste women have gone through. Dalit and Women are not caste or gender category, it is an experiential category. He is the one who can tell and support women. BN Rao and Ambedkar are two most important people who have the actual power.

What is the problem? In 1937-1940 Jinnah said that separate Pakistan is essential. Congress never thought that Hnnah would get this form of traction. When the CAD Debate is happening the violence also begins, both sides become very tense. Violence was brutal, at that time there were millions of Mulsolims that did not go. Therefore there is a concern in CAD that this Congress dominated, Hindu dominated group will give us secular laws. After the 47 violence they had to prove their patriotism to the nation. Even at this point, the CAD did not want any person to feel left out. They had thus made Art. 44 but it was postponed to make the community feel inclusive. This is what Ambedkar is referring to, and thus while we need to improve their living conditions, we cannot push them or shove it down the Constitution. 

If we say that there is a partition violence and there is a partition history, and there is an anxiety in the minorities. In this logic one must ask - a : is it the case that the fundamentalist of all religions co-operate when it comes to the women's question, b : do we want to wait till there is an internal critical mass available that is implosition from within. It is a negotiation and there cannot be one answer. 

We are trying to understand the nature of women's movement in the 1920's, take note of the fact how far women's movement has moved and yet how little we have achieved. There is an argument regarding adoption, Hansa Mehta talks about the need for adoption, Putra is spiritual movement and this world-ly movement, Vaitarni and Pind Dan. Pg. 222 (Founding Mothers of the Indian Constitution) Policy Bazaar ad - Man should care for women when he is alive, but he should also care for women when he is dead. How? Through capitalism, you pay a premium and you die. Womens identity is attached to her dead husband for all her life. Whenver we bring in property, sisters are normally on the losing end and end up spending more money on legal fees as compared to the brothers. 

Androcentric = Male centric
Nationalism was founded on the idea that the nation was founded on an agnate relationship among its citizens

Girls not as citizens but rather as mothers of citizens. Essentialise the identity. Mother is an essentially desexualised person, pure and chaste. Overwhelming representation of woemn as loving, caring and does not have her own identity. Women and mother are almost conjoint. Women and motherhood is a constructed goal. Bhargavdas understands it as a instrumental category--Women are to be good, because the children will be better.

In 1931, Karachi resolution is passed, on one side we have Gandhi (upvas dictatorship) who said we will only use term 'swaraj', while Bose and Nehru argued 'purna swaraj'. In india the language or swaraj made so that we make our demands legible to the Britishers. As we are making this demand, the self becomes fractured - women, dalit, tribals. When we talk about swaraj, it becomes a fractured swaraj even if we reduce the muslim position it is a fractured swaraj. That is the logic. Because of this the roots of Art. 15, 19, 21 etc are founded. Nehru Report and Karachi Resolution - Everyone will be treated in the same way - for all religions as personal law and fundamental right. Women argue that their Swaraj is not real Swaraj. Women are using the same language vis their leaders that the men are using against the colonizer. 12 women are making such a heavy difference, making the law very complicatd. What you are demanding you must also give that, this was made up by the claims made by women and dalit.  


How do you deal with the idea that women are generally understood as contended slaves. Is it true that slaves have no understanding of what is good for them? As provided under Pg. 230 it is not that they have no understanding of what is good for them, but the lack of options makes any such understanding tragic and useless.

One is a natal family, one is a national family and one is the world as a family (vasudhaiva kutumbakam). Where is the individual?, In the family the individual is part of gotra, in the nation one is an Indian, and then one is citizen or human (UNDHR). There is an I that needs to be dissolved continuously. The concern I should to my husband is not reciprocated to me, but that I think is /natural/.

Hindu Jurisprudential conceptualisation of sexual difference. We have been accused that it is borrowed from various parts of the World. This is not the case there is no patent on constitutional ideas. There has been accusation that 'Where is the Hindu Bharatiya in this'? The villages of India are a den of superstition, blindfaith and thus it is good that there is no Hindu Jurisprudence in the Constitution.

Linda Colley book - *Gun, Ship and Pen* argues that the average age of the Constitution is 16 years. If your reality is not congruent to the Constitution, then you can change your reality to become congruent to the Constitution. Or possibly try to incorporate the reality into the Constitution. Constitution C1 cannot argue that we will create a new reality R0, theoretically you cannot have a blank page but you can always change the reality. It cannot be that both exist as divergent paths. There is nothing sacred about the Constitution in itself.

On behalf - taking the onus, even if the represented group does not recognise the need for such a right. Representative - the representated group send the representative to put forth the point. If you want our Indians living in the West to be equally treated, we must also equally recognise /inter-se/ equality. When women ask for UCC they are not deciding that X religion is better than Y religion. They collectively posit that religious jurisprudence as a whole is problematic and thus 'human rights' model must be established, one that is founded on 'rational' policies.
