:PROPERTIES:
:ID:       02c89e5b-b670-4155-a4d9-ce0c7f4ae721
:END:
#+title: A naive review of Kant's positions

- Source: History of Western Philosophy by Russell

* The Start
Kant as far as I understand, develops his elaborate thesis with the intent to refute the /agnositicsm/ that Hume brings to the project of philosophy. This empericism made it difficult to clearly differentiate between rational belief and credulity (the quality of believing in something without needing proper proof). If every idea was founded on an 'impression' and they themselves had no specific source or cause other than simply being 'external to the mind' then the rational argument still a byproduct of this impression is similar to blatent assertions which are also founded on impressions though it may not be as supported by the realities of the world outside. This problem in Hume generated a subtle and profound response in Germany where Hegel Schelling and Kant developed a system of though that maintained the subjective tendencies which were first highlighted by Decarte though the cogito.

** Key Positions of the German School
- They prioritise mind over matter
- Vehement rejection of the utilitarian systems in favour of an alternate idea
- Very pro-orthodoxy and wanted to maintain the status quo, while their ideas are quite liberal they were often employed in the defence of the existing institutions.

* Ideas
- The crux of COPR is that while knowledge cannot transcend experiance, it nonetheless can have an a priori nature and knowledge which is a priori embraces parts which are not only deduced through logic (something otherworldly and transcendental)
- There are two key antagonisms that require attention
  - Analytic-Synthetic
    - Analytic refers to positions where the predicate contains something that is inherent about the subject = A tall man is a man. This predicate here contains the manliness that is inherent to the subject that is the man.
    - Synthetic refers to statements where the predicate and the subject have are not inherently related - Tuesday is a wet day. The predicate here contains no inherent quality of the subject. Additionally, the mere understanding of 'concepts' will not allow us to make the above sentance
    - The problem in this neat distinction is that while those statements derived out of experiance are generally synthetic, Kant will no go as far as to argue that synthetic statements can only be made through experiance.
  - Emperical-A Priori
    - Experical is that which is felt through the sense perception or which is vicariously felt through the testimony of an other.
    - A Priori refers to those propositions which although may be elicited through expression, it is known by virtue of something other than experiance.
      - The example that Russel gives is that a child may be taught that 2+2 = 4 through a physical demonstration of four marbles but he retains it and subsequently applies it to other such problems as a result of not only the sense experiance but through is a priori understanding of the concept. A purely empical view would restrict the function of addition only when 2 and 2 are involved, because we have no emperical evidence to sugges that what was true in the case of those four marbles will be true for a 100 of them, unless it is actually performed. Through the demonstration, emperically he only understood that the adding two marbles to two marbles results in four of them, but through the function of the a priori reasoning he was able to understand that this applies to all situations where the addition of two integers is to be conducted. 
    
