:PROPERTIES:
:ID:       ddc2d99f-281f-4561-870a-06ef330ee591
:END:
#+title: Payment of Bonus


Mill Owners Association, Bombay v. Rashtriya Mill Mazdoor Sangh, Bombay (1950 LAT)
Created a formula for the payment of bonus, called ‘Full Bench Formula’
The PoB is based on this formula and was recognised by SC in 1959 in Associated Cement Company Ltd v. Workmen (1959)

* Objectives of the Act
- To make provision for statutory payment of bonus upon the employers of the establishment covered under the Act
- To make provision for payment of minimum and maximum bonus and to link the payment of bonus with the principles of set on and set off. 
- Prescribe a standard formula for the payment of bonus
- To provide machinery for redressal of grievances related to payment of bonus. 

* Applicability of the Act
- Every factory and establishment where 20 or more employees are working or where working on any day in the preceding 12 months.
- Even if the number of employees are	 falling below 20 the obligation for payment of bonus will still continue. However the number of employees can be reduced by the AG by a notification in the official gazette but in no case will the no. of employees be less than 10.
- If the establishment has multiple branches, they will be considered as one if they provide a singular consolidated balacesheet.
- Industrial Establishment = Establishment has not been defined under the Act, it defines establishment in public and private sector.
  - Public = Minimum 40% or more holding is of CG or RBI or collectively.
  - Public = Not public.
  - Establishment = Generally refers to a place which is fixed for buiseness with necessary equipment, any office or place of buiseness.
- Under Section 16 the bonus is to be given in the first 5 financial years, only if there is profit. But if some branches of the establishment 


* Employees Entitled
- Provided that the wages are up to Rs. 21000 per month and the employee has worked at least 30 days. 
- If the same establishment has multiple branches in the same State or in different States, then obligation for payment of bonus will arise if the no. of employees for all the branches are 20 or more. 
- Test in such cases provided in the act is that - whether the profit and loss accounts, (balance sheet) is the same. If yes, then all the branches are considered together for calculation of eligibility. 
- Even if the premises remain the same but the establishment is operating separately then the employees cannot claim bonus, if in the specific establishment 20 employee rule is not fulfilled. 
- This is to be read Section 32 of the PoB Act - Non-applicability of the Act. 

* Definitions
- Salary or Wage - Basic + DA + Retaining Allowance (If Paid).
- Minimum Bonus - 8.33 % of Wage. Maximum Bonus - 20% of Wage
- Minimum Bonus = 8.33% or 100 Rupees whichever is higher. 
- If the worker is less than 15 years of age, 100 to be substituted with 60
- May pay higher bonus also but only up to 20% bonus payment will be exempted from tax, the excess will be taxed. 
- Available and Allocable Surplus
  - Available Surplus = Section 5 : For calculation of bonus the gross profit of the company is considered, of which some deductions are made and the amount that remains is called available surplus.
  - Allocable Surplus = Out of this 60-67% of Available Surplus is allocated for payment of bonus. 60 in case of Indian Companies, 67 in case of Foreign Companies. 
- Set-on and Set-off - Section 15
  - Set-on : Carryforward of profit of company
  - Set-off : Carryforward of losses of company

* Calculation of Bonus
- Calculate the gross profit :
  - In case of banking company (per Banking Regulation Act) the calculation is done as per 1st Schedule, for other companies it is 2nd schedule
  - To calculate available surplus = a + b.
  - a = gross profit - depreciation (u/s 32 of IT Act) - development rebate or investment allowance or development allowance - direct taxes payable for the accounting year (calculated as per S. 7) - sums specified in 3rd Schedule
  - b = direct taxes (calculated as per S. 7) - amount of bonus for the immediately preceding accounting year.
  b is the portion for the previous accounting year, which is added to the value of the first accounting year.
- Gross Profit - Reduction of Prior Charges = Available Surplus
- Calculate the allocable surplus = 60-67% of the available surplus Section 5, 6, 7
- Set-on and Set-off be provided for - Section 15 r/w 4th Schedule of the PoB Act

* Rules regarding set-on and set-off:
- Is to be done up to four accounting years, including the year when the first set-on or set-off has been made. 
- In case of consecutive set-on or set-off, the amount which has been first set-on or set-off shall be utilised. 
- Three situations
  - If Allocable Surplus < Minimum Bonus = minimum bonus shall be paid and it shall be setoff
  - If Allocable Surplus = Minimum Bonus = minimum bonus shall be paid as bonus (no set-on or set-off)
  - If Allocable Surplus > Maximum Bonus = maximum bonus shall be paid as bonus (set-on)
- The entire amount remaining technically should be set-on, the proviso is that the surplus amount will be carry forwarded subject to maximum of maximum bonus (jitna maximum bonus company pay kar rahi hai, utna hi value set-on kar sakte hai)
- Note : In case of an employee receiving salary or wage between 7,000 or the minimum wage for the scheduled employment whichever is higher and rupees 21,000 per month, the bonus payable to him shall be calculated as if his salary or wage were Rs. 7000 or minimum wage fixed by the AG whichever is higher. (Section 12 of the PoB with 2015 Amendment Act)
- Is an employee entitled to get bonus on the basis of his entire salary or wage
  - Answer is yes where the wage or salary is less than 7000 per month
  - Where the wages is between 7000 and 21000 then the wage is considered as if it is 7000.
  - Where the wage is higher than 21000 the rule will not apply

* Jalan Trade Company Pvt. Ltd. v. Mill Mazdur Sabha
- Express Newspapers was decided by SC. Contention was that under 19(1)(a) speech and expression covers freedom of the press also. When such freedom is there 19(1)(a) r/w 19(1)(g) gives Press Groups the right to function freely both commercially and functionally. The Act in question if enacted will take away the freedom of press, the Press Groups at the time were not industriaised and was run by prominent individuals rather than being a commercial activity. As it became an industrial activity, it was seen that all establishments are not of the same size and if the impugned Act is initiated, (payment of MW to Journalists), it will lead to the closure of those Press Groups who are smaller in size. Journalists cannot be considered as an industrial worker. Labour Law is not to be made applicable, the decision which was based on V.N.N Sinha v. Bihar Journals Ltd. Patna HC 1953 where the Court held that newspaper employee is not equal to industrial worker meaning that the labour law will not be applicable. In Express Newspaper it was opined that though they are not industrial workers, it does not include Press Groups from speicial laws such as labour and revenue. Based on the nature of the industry, the Parliament shall enact a law on the following aspects

  - Notice Period
  - Bonus
  - Minimum Wages
  - Weekly Rest
  - Leaves
  - PF and Gratuity

- Based on this, when PoW came up, it was challenged on the basis of the principles of Express Newspapers which required that there should be a 'specific law'. They argued that Payment of Bonus Act cannot be made, Payment of Bonus for Working Journalists should be made.

- They also challenged specific provisions such Section 10 of the Act, which requires the payment of minimum bonus.

** Court held:
- While the requirements of Express Newspapers have not be followed, it does not mean that the Parliament cannot make any law for working journalists. The POBA will still be liable.
- It also observed that excessive powers have been given under 



* Section 13
Under Section 8, 30 working days implies that the worker must have actually worked on those days. Wages: monetery compensation for the work done by the Employee. Remuneration: where the employee has not worked but is still getting paid for it is remuneration - 15 Aug for instance. Now here 30 working days = actual work, excluding all forms of holidays.

If the criteria has not been fulfilled,

If 30 days have not been fulfilled then following may be added to compute the 
- Period of Layoff
- Paid Leave
- Absence due to temporary disablement
- Maternity Leave



