:PROPERTIES:
:ID:       c0d779e9-d04e-4e75-990f-d1c1ea2dd8a4
:END:
#+title: Police Legitimacy

The claims in existing literature is that if only the people could feel that the police treatt them fairly the y will be likely to trust and obey them. And that this obeying serves as a fair statistic for legitimacy. Tankebe argues that utilitarian factors such as 'effectiveness' play a greater rolein shaping publicco-op with the police. For him the lack of legitimacy is the inability to decouple the legitimacy of the post-colonial state from its colonial predecessor. Reiner argues that the police was previously a defiled institution but came to be a part of the British National Identity in the 20th century because of the inclusion of the working class into the mainstream society. The police then undervent a serious of scandles leading to delegitimisation. He then says that we are currently in a 'post-legitimation' politics characterised by ambiguity and volatility in police representation and evaluation. For him thus the legitimacy of the police is grounded in logitudinal ethnographic methods and antrhopoloogical theories of authority and meaning making. The author takes an anthropological approach to develop her arguments herein

She argues that for a majority of the police force there is little to no upward mobility through the four ranks. Movement within the ranks is also slow and highly politicised. BEcause the Constable comprises of 90 percent of he police of India, they constitute the face of policing. But because they lack any form of authority oth legally and otherwise, the are often per Baxi called a despised minority. They are a social minority may not be a numerical one. They are also expeced to often perform non-mandated domestic duties for senior offers. This problem cannot be simplified merely on the basis of caste conflict. They generally come from relatively poor familie in rural villages or small towns. They are legally prohibited from initiative or engaging in any activity relating to the criminal investigation without the direct instructions by sub-inspector.
# this has a decidedly colonial aspect which must be mentioned.

While the public sees the constable as lazy, lying cheats, the senior offers characterise them as simpletons plagued by the village mind or rural psyche. There is a implication that this nationally immature majority of the police force is considered to be made up of persons who are not merely lowrer in rank but also inferior in substance as political subjects to say noting of being inferior as legal authortiies. The strog conception of the masses of constables in INdia constituting mostly poor specimens of humanity is propounded most heavily by their own senior officers who tend to come from higher socioeconomic calsses with greater education resources etc. The subordination is thus a result of both the formal subordination and other forms of socil inequality included the involcation of forms of authority external and superior tostate law - kinship and cosmological position. 
